name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Elm tests
        run: npm test
      
      - name: Format check
        run: npm run format -- --validate
      
      - name: Build project
        run: npm run build

#      TODO: add elm-review enforcement in the future
#      - name: Run elm-review
#        run: npm run review