name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Format check
        run: npm run format -- --validate

      - name: Run Elm tests
        run: npm test
      
      - name: Build project
        run: npm run build

#      TODO: add elm-review enforcement in the future
#      - name: Run elm-review
#        run: npm run review

  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: test  # Only run e2e tests if unit tests pass
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      
      - name: Build project for e2e tests
        run: npm run build
      
      - name: Run e2e tests
        run: npm run test:e2e
        env:
          CI: true
      
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: Upload test artifacts (screenshots, videos, traces)
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-test-artifacts
          path: test-results/
          retention-days: 30
      
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: ${{ !cancelled() }}
        with:
          name: Playwright E2E Tests
          path: test-results/results.xml
          reporter: java-junit
          fail-on-error: false
      
      - name: Comment test results on PR
        uses: actions/github-script@v7
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        with:
          script: |
            const fs = require('fs');
            try {
              const reportPath = 'playwright-report/index.html';
              if (fs.existsSync(reportPath)) {
                const comment = `## 🎭 Playwright E2E Test Results\n\n` +
                  `The e2e tests have completed. ` +
                  `[View detailed HTML report in artifacts](${context.payload.pull_request.html_url}/checks)`;
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
              }
            } catch (error) {
              console.log('Could not post test results comment:', error.message);
            }